PUT http://localhost:3004/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2UyQGVtYWlsLmZha2UiLCJpYXQiOjE1OTQxNTMyMDIsImV4cCI6MTU5NDE1NjgwMn0.gnsduYIRjuIvDMNYxVW3FLAVV-epz0Us5rNa0LHO3Do
Content-Type: application/json

{
  "token": "46f7c0e8-752c-444d-98f1-4184dd2428b5",
  "secret": "jw4vzq7y"
}
