PUT http://localhost:3004/credentials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2VAZW1haWwuZmFrZSIsImlhdCI6MTU5Mzc4Njc0MCwiZXhwIjoxNTkzNzkwMzQwfQ.zwIHcG-crLDCRP47uW91sxkGbGh4AJgG2W-4NZZnVts
Content-Type: application/json

{
  "token": "1412b8e3-78f6-4ff6-bb5b-8bcc759e64da",
  "secret": "lcsa3zhu"
}
